### ISSUE TITLE
Updated NatureOverhaul to latest Minecraft, using Forge API

### ISSUE THREAD

**Issue by GotoLink** [Clintonio/NatureOverhaul#9]
I removed all Mojang class edits.
I also removed dependency on ModOptionsAPI (it is still usable through reflection, but use @WyrdOne fork)
Moved to ForgeAPI which, thanks to its event system, could make this possible.

See my fork at GotoLink/NatureOverhaul.

**Comment by Clintonio** [comment]
I've tagged a working 1.7.10 release. 1.12.2 is under way.
